package com.ids;
import java.util.List;

/**
 * A single detection rule that can produce zero or more alerts for each incoming event.
 *
 * Implementations should be lightweight and stateless where possible, since they may be
 * invoked for every event in a high-throughput stream.
 */
public interface RuleEngineRules {

    /**
     * Evaluate the given event and return any resulting alerts.
     *
     * @param event the event to evaluate
     * @return list of alerts generated by this rule (may be empty but not null)
     */
    List<Alert> onEvent(Event event);

    /**
     * Returns a stable name for this rule used in reporting, logging, and debugging.
     */
    String getName();
}
